export const StandingData = [
  {
    p: '1',
    name: 'BG Pathum United',
    initials: 'BGPU',
    imageXS: '/static/images/clubs/bgpu@x1.png',
    imageSM: '/static/images/clubs/bgpu@x2.png',
    image: '/static/images/clubs/bgpu.png',
    url: 'http://www.bgputd.com/',
    pl: '15',
    gd: '+22',
    pts: '41',
  },
  {
    p: '2',
    name: 'Port Fc',
    initials: 'PORT',
    imageXS: '/static/images/clubs/port@x1.png',
    imageSM: '/static/images/clubs/port@x2.png',
    image: '/static/images/clubs/port.png',
    url: 'https://www.facebook.com/portfootballclubofficial/',
    pl: '14',
    gd: '+22',
    pts: '34',
  },
  {
    p: '3',
    name: 'Singha Chiangrai United',
    initials: 'CRUTD',
    imageXS: '/static/images/clubs/crutd@x1.png',
    imageSM: '/static/images/clubs/crutd@x2.png',
    image: '/static/images/clubs/crutd.png',
    url: 'http://www.mtutd.tv/',
    pl: '14',
    gd: '+9',
    pts: '25',
  },
  {
    p: '4',
    name: 'Ratchaburi Mitrphol FC',
    initials: 'RBMFC',
    imageXS: '/static/images/clubs/rat@x1.png',
    imageSM: '/static/images/clubs/rat@x2.png',
    image: '/static/images/clubs/rat.png',
    url: 'https://www.facebook.com/RBMFCOFFICIAL/',
    pl: '14',
    gd: '+9',
    pts: '25',
  },
  {
    p: '5',
    name: 'Buriram United',
    initials: 'BRUTD',
    imageXS: '/static/images/clubs/btutd@x1.png',
    imageSM: '/static/images/clubs/btutd@x2.png',
    image: '/static/images/clubs/btutd.png',
    url: 'https://www.buriramunited.com/',
    pl: '15',
    gd: '+8',
    pts: '23',
  },
  {
    p: '6',
    name: 'Samut Prakan City',
    initials: 'SPC',
    imageXS: '/static/images/clubs/SPC@x1.png',
    imageSM: '/static/images/clubs/SPC@x2.png',
    image: '/static/images/clubs/SPC.png',
    url: 'http://www.samutprakancityfc.com/',
    pl: '15',
    gd: '+6',
    pts: '22',
  },
  {
    p: '7',
    name: 'Chonburi FC',
    initials: 'CHON',
    imageXS: '/static/images/clubs/chon@x1.png',
    imageSM: '/static/images/clubs/chon@x2.png',
    image: '/static/images/clubs/chon.png',
    url: 'http://chonburifootballclub.com/',
    pl: '15',
    gd: '-6',
    pts: '22',
  },
  {
    p: '8',
    name: 'SCG Muangthong United',
    initials: 'MTUTD',
    imageXS: '/static/images/clubs/mtutd@x1.png',
    imageSM: '/static/images/clubs/mtutd@x2.png',
    image: '/static/images/clubs/mtutd.png',
    url: 'http://www.mtutd.tv/',
    pl: '15',
    gd: '+3',
    pts: '21',
  },
  {
    p: '9',
    name: 'True Bangkok United',
    initials: 'bufc',
    imageXS: '/static/images/clubs/bufc@x1.png',
    imageSM: '/static/images/clubs/bufc@x2.png',
    image: '/static/images/clubs/bufc.png',
    url: 'http://www.truebangkokunitedfc.com/',
    pl: '15',
    gd: '+1',
    pts: '20',
  },
  {
    p: '9',
    name: 'Sukhothai FC',
    initials: 'STFC',
    imageXS: '/static/images/clubs/suk@x1.png',
    imageSM: '/static/images/clubs/suk@x2.png',
    image: '/static/images/clubs/suk.png',
    url: 'http://www.mtutd.tv/',
    pl: '15',
    gd: '-2',
    pts: '20',
  },
  {
    p: '10',
    name: 'Police Tero FC',
    initials: 'POLFC',
    imageXS: '/static/images/clubs/tero@x1.png',
    imageSM: '/static/images/clubs/tero@x2.png',
    image: '/static/images/clubs/tero.png',
    url: 'http://www.policetero.com/stadium/',
    pl: '15',
    gd: '-9',
    pts: '19',
  },
  {
    p: '12',
    name: 'Suphanburi Football Club',
    initials: 'SPFC',
    imageXS: '/static/images/clubs/suphan@x1.png',
    imageSM: '/static/images/clubs/suphan@x2.png',
    image: '/static/images/clubs/suphan.png',
    url: 'http://www.suphanburifootballclub.com/',
    pl: '15',
    gd: '-5',
    pts: '17',
  },
  {
    p: '13',
    name: 'Nakhonratchasima Mazda FC ',
    initials: 'NRMFC',
    imageXS: '/static/images/clubs/swat@x1.png',
    imageSM: '/static/images/clubs/swat@x2.png',
    image: '/static/images/clubs/swat.png',
    url: 'https://www.facebook.com/swatcatofficial/',
    pl: '15',
    gd: '-8',
    pts: '16',
  },
  {
    p: '14',
    name: 'PT Prachuap FC',
    initials: 'PTPRCHFC',
    imageXS: '/static/images/clubs/pt@x1.png',
    imageSM: '/static/images/clubs/pt@x2.png',
    image: '/static/images/clubs/pt.png',
    url: 'https://www.facebook.com/PrachuapFc2011/',
    pl: '15',
    gd: '-6',
    pts: '14',
  },
  {
    p: '15',
    name: 'Rayong FC',
    initials: 'Rayong FC',
    imageXS: '/static/images/clubs/ray@x1.png',
    imageSM: '/static/images/clubs/ray@x2.png',
    image: '/static/images/clubs/ray.png',
    url: 'https://www.facebook.com/Rayong.FC.Fanpage/',
    pl: '15',
    gd: '-21',
    pts: '10',
  },
  {
    p: '16',
    name: 'Trat FC',
    initials: 'Trat FC',
    imageXS: '/static/images/clubs/trat@x1.png',
    imageSM: '/static/images/clubs/trat@x2.png',
    image: '/static/images/clubs/trat.png',
    url: 'https://www.facebook.com/tratfc2012/',
    pl: '15',
    gd: '-18',
    pts: '7',
  },
]

export const clubs = [
  {
    name: 'Buriram United',
    initials: 'BRUTD',
    imageXS: '/static/images/clubs/btutd@x1.png',
    imageSM: '/static/images/clubs/btutd@x2.png',
    image: '/static/images/clubs/btutd.png',
    url: 'https://www.buriramunited.com/',
  },
  {
    name: 'Chonburi FC',
    initials: 'CHON',
    imageXS: '/static/images/clubs/chon@x1.png',
    imageSM: '/static/images/clubs/chon@x2.png',
    image: '/static/images/clubs/chon.png',
    url: 'http://chonburifootballclub.com/',
  },
  {
    name: 'Nakhonratchasima Mazda FC ',
    initials: 'NRMFC',
    imageXS: '/static/images/clubs/swat@x1.png',
    imageSM: '/static/images/clubs/swat@x2.png',
    image: '/static/images/clubs/swat.png',
    url: 'https://www.facebook.com/swatcatofficial/',
  },
  {
    name: 'Police Tero FC',
    initials: 'POLFC',
    imageXS: '/static/images/clubs/tero@x1.png',
    imageSM: '/static/images/clubs/tero@x2.png',
    image: '/static/images/clubs/tero.png',
    url: 'http://www.policetero.com/stadium/',
  },
  {
    name: 'Port FC',
    initials: 'PORT',
    imageXS: '/static/images/clubs/port@x1.png',
    imageSM: '/static/images/clubs/port@x2.png',
    image: '/static/images/clubs/port.png',
    url: 'https://www.facebook.com/portfootballclubofficial/',
  },
  {
    name: 'Ratchaburi Mitrphol FC',
    initials: 'RBMFC',
    imageXS: '/static/images/clubs/rat@x1.png',
    imageSM: '/static/images/clubs/rat@x2.png',
    image: '/static/images/clubs/rat.png',
    url: 'https://www.facebook.com/RBMFCOFFICIAL/',
  },
  {
    name: 'Rayong FC',
    initials: 'Rayong FC',
    imageXS: '/static/images/clubs/ray@x1.png',
    imageSM: '/static/images/clubs/ray@x2.png',
    image: '/static/images/clubs/ray.png',
    url: 'https://www.facebook.com/Rayong.FC.Fanpage/',
  },
  {
    name: 'Samut Prakan City',
    initials: 'SPC',
    imageXS: '/static/images/clubs/SPC@x1.png',
    imageSM: '/static/images/clubs/SPC@x2.png',
    image: '/static/images/clubs/SPC.png',
    url: 'http://www.samutprakancityfc.com/',
  },
  {
    name: 'SCG Muangthong United',
    initials: 'MTUTD',
    imageXS: '/static/images/clubs/mtutd@x1.png',
    imageSM: '/static/images/clubs/mtutd@x2.png',
    image: '/static/images/clubs/mtutd.png',
    url: 'http://www.mtutd.tv/',
  },
  {
    name: 'Singha Chiangrai United',
    initials: 'CRUTD',
    imageXS: '/static/images/clubs/crutd@x1.png',
    imageSM: '/static/images/clubs/crutd@x2.png',
    image: '/static/images/clubs/crutd.png',
    url: 'http://www.mtutd.tv/',
  },
  {
    name: 'Sukhothai FC',
    initials: 'STFC',
    imageXS: '/static/images/clubs/suk@x1.png',
    imageSM: '/static/images/clubs/suk@x2.png',
    image: '/static/images/clubs/suk.png',
    url: 'http://www.mtutd.tv/',
  },
  {
    name: 'Suphanburi Football Club',
    initials: 'SPFC',
    imageXS: '/static/images/clubs/suphan@x1.png',
    imageSM: '/static/images/clubs/suphan@x2.png',
    image: '/static/images/clubs/suphan.png',
    url: 'http://www.suphanburifootballclub.com/',
  },
  {
    name: 'True Bangkok United',
    initials: 'bufc',
    imageXS: '/static/images/clubs/bufc@x1.png',
    imageSM: '/static/images/clubs/bufc@x2.png',
    image: '/static/images/clubs/bufc.png',
    url: 'http://www.truebangkokunitedfc.com/',
  },
  {
    name: 'PT Prachuap FC',
    initials: 'PTPRCHFC',
    imageXS: '/static/images/clubs/pt@x1.png',
    imageSM: '/static/images/clubs/pt@x2.png',
    image: '/static/images/clubs/pt.png',
    url: 'https://www.facebook.com/PrachuapFc2011/',
  },
  {
    name: 'Trat FC',
    initials: 'Trat FC',
    imageXS: '/static/images/clubs/trat@x1.png',
    imageSM: '/static/images/clubs/trat@x2.png',
    image: '/static/images/clubs/trat.png',
    url: 'https://www.facebook.com/tratfc2012/',
  },
]
