export const ClubsList = [
    {
      name:'BG Pathum United',
      initials:'BGPU',
      imageXS: '/clubs/bgpu@x1.png',
      imageSM: '/clubs/bgpu@x2.png',
      image: '/clubs/bgpu.png',
      url: 'http://www.bgputd.com/',
    },
    {
      name:'Buriram United',
      initials:'BRUTD',
      imageXS: '/clubs/btutd@x1.png',
      imageSM: '/clubs/btutd@x2.png',
      image: '/clubs/btutd.png',
      url: 'https://www.buriramunited.com/',
    },
    {
      name:'Chonburi FC',
      initials:'CHON',
      imageXS: '/clubs/chon@x1.png',
      imageSM: '/clubs/chon@x2.png',
      image: '/clubs/chon.png',
      url: 'http://chonburifootballclub.com/',
    },
    {
      name:'Nakhonratchasima Mazda FC ',
      initials:'NRMFC',
      imageXS: '/clubs/swat@x1.png',
      imageSM: '/clubs/swat@x2.png',
      image: '/clubs/swat.png',
      url: 'https://www.facebook.com/swatcatofficial/',
    },
    {
        name:'Police Tero FC',
        initials:'POLFC',
        imageXS: '/clubs/tero@x1.png',
        imageSM: '/clubs/tero@x2.png',
        image: '/clubs/tero.png',
        url: 'http://www.policetero.com/stadium/',
    },
    {
        name:'Port FC',
        initials:'PORT',
        imageXS: '/clubs/port@x1.png',
        imageSM: '/clubs/port@x2.png',
        image: '/clubs/port.png',
        url: 'https://www.facebook.com/portfootballclubofficial/',
    },
    {
        name:'Ratchaburi Mitrphol FC',
        initials:'RBMFC',
        imageXS: '/clubs/rat@x1.png',
        imageSM: '/clubs/rat@x2.png',
        image: '/clubs/rat.png',
        url: 'https://www.facebook.com/RBMFCOFFICIAL/',
    },
    {
        name:'Rayong FC',
        initials:'Rayong FC',
        imageXS: '/clubs/ray@x1.png',
        imageSM: '/clubs/ray@x2.png',
        image: '/clubs/ray.png',
        url: 'https://www.facebook.com/Rayong.FC.Fanpage/',
    },
    {
        name:'Samut Prakan City',
        initials:'SPC',
        imageXS: '/clubs/SPC@x1.png',
        imageSM: '/clubs/SPC@x2.png',
        image: '/clubs/SPC.png',
        url: 'http://www.samutprakancityfc.com/',
    },
    {
        name:'SCG Muangthong United',
        initials:'MTUTD',
        imageXS: '/clubs/mtutd@x1.png',
        imageSM: '/clubs/mtutd@x2.png',
        image: '/clubs/mtutd.png',
        url: 'http://www.mtutd.tv/',
    },
    {
        name:'Singha Chiangrai United',
        initials:'CRUTD',
        imageXS: '/clubs/crutd@x1.png',
        imageSM: '/clubs/crutd@x2.png',
        image: '/clubs/crutd.png',
        url: 'http://www.mtutd.tv/',
    },
    {
        name:'Sukhothai FC',
        initials:'STFC',
        imageXS: '/clubs/suk@x1.png',
        imageSM: '/clubs/suk@x2.png',
        image: '/clubs/suk.png',
        url: 'http://www.mtutd.tv/',
    },
    {
        name:'Suphanburi Football Club',
        initials:'SPFC',
        imageXS: '/clubs/suphan@x1.png',
        imageSM: '/clubs/suphan@x2.png',
        image: '/clubs/suphan.png',
        url: 'http://www.suphanburifootballclub.com/',
    },
    {
        name:'True Bangkok United',
        initials:'bufc',
        imageXS: '/clubs/bufc@x1.png',
        imageSM: '/clubs/bufc@x2.png',
        image: '/clubs/bufc.png',
        url: 'http://www.truebangkokunitedfc.com/',
    },
    {
        name:'PT Prachuap FC',
        initials:'PTPRCHFC',
        imageXS: '/clubs/pt@x1.png',
        imageSM: '/clubs/pt@x2.png',
        image: '/clubs/pt.png',
        url: 'https://www.facebook.com/PrachuapFc2011/',
    },
    {
        name:'Trat FC',
        initials:'Trat FC',
        imageXS: '/clubs/trat@x1.png',
        imageSM: '/clubs/trat@x2.png',
        image: '/clubs/trat.png',
        url: 'https://www.facebook.com/tratfc2012/',
    },
  ]
  